// Generated by CoffeeScript 1.9.0
(function() {
  var Game,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Game = (function() {
    function Game(_at_ctxFront, _at_ctxBack, _at_ctxWeather, _at_width, _at_height) {
      this.ctxFront = _at_ctxFront;
      this.ctxBack = _at_ctxBack;
      this.ctxWeather = _at_ctxWeather;
      this.width = _at_width;
      this.height = _at_height;
      this.myLoop = __bind(this.myLoop, this);
      this.resources = [];
      this.map = null;
      this.peoples = [];
      this.alivePeople = 0;
      this.boats = [];
      this.buildings = [];
      this.technologies = [];
      this.priorities = [];
      this.fps = 50;
      this.weather = 0;
      this.timeSameWeather = 0;
      this.weatherElements = [];
      this.weatherDraw = false;
      this.interval = null;
      this.realInterval = 0;
      this.score = 1;
      this.maxPop = 0;
      this.spritePeople = new Spritesheet('img/spritePeople.png', 8);
      this.spritePeopleElements = [];
      this.spritePeopleElements.push(new SpriteElement(this.spritePeople, 0, 0));
      this.spritePeopleElements.push(new SpriteElement(this.spritePeople, 1, 0));
      this.spritePeopleElements.push(new SpriteElement(this.spritePeople, 2, 0));
      this.spritePeopleElements.push(new SpriteElement(this.spritePeople, 3, 0));
      this.spriteBuildings = new Spritesheet('img/spriteBuildings.png', 10);
      this.WEATHER_SUN = 0;
      this.WEATHER_RAIN = 1;
      this.WEATHER_WARM = 2;
      this.WEATHER_SNOW = 3;
      this.BUILDING_TYPE_TEMPLE = 0;
      this.BUILDING_TYPE_HOUSE = 1;
      this.BUILDING_TYPE_FARM = 2;
      this.BUILDING_TYPE_GRANARY = 3;
      this.BUILDING_TYPE_PASTURE = 4;
      this.BUILDING_TYPE_SAWMILL = 5;
      this.BUILDING_TYPE_HUNTING_LODGE = 6;
      this.BUILDING_TYPE_HARBOR = 7;
      this.BUILDING_NUMBER_HARBOR = 0;
      this.GRANARY_COST = 20;
      this.TEMPLE_COST = 40;
      this.HOUSE_COST = 10;
      this.FARM_COST = 10;
      this.HUNTING_LODGE_COST = 10;
      this.PASTURE_COST = 20;
      this.HARBOR_COST = 30;
      this.SAWMILL_COST = 10;
      this.BOAT_COST = 5;
      this.FOOD_COMSUPTION = 1;
      this.MAX_AGE = 50;
      this.DEATH_FROM_ICE = 0;
      this.PRIORITY_IDDLE = 0;
      this.PRIORITY_FOOD = 1;
      this.PRIORITY_WOOD = 2;
      this.PRIORITY_FAITH = 3;
      this.PRIORITY_GRANARY = 4;
      this.PRIORITY_HOUSE = 5;
      this.PRIORITY_HARBOR = 6;
      this.FOOD_FARM = 8;
      this.FOOD_PASTURE = 12;
      this.FOOD_HUNTING = 4;
      this.FOOD_HUNTING_FIRE = 6;
      this.FOOD_BOAT = 2;
      this.TECH_FIRE = 0;
      this.TECH_BREEDING = 1;
      this.TECH_WHEEL = 3;
      this.TECH_AGRICULTURE = 4;
      this.TECH_PAPER = 6;
      this.TECH_MAP = 7;
      this.TECH_ARCHITECTURE = 8;
      this.TECH_FISH = 10;
      this.MANA = 0;
      this.FOOD = 1;
      this.WOOD = 2;
    }

    Game.prototype.init = function() {
      var i, _i;
      this.map = new Map(this.ctxBack, this.width, this.height);
      this.map.init();
      this.map.draw();
      this.resources = [10, 10, 50];
      for (i = _i = 1; _i <= 10; i = ++_i) {
        this.addPeople();
      }
      this.build(this.BUILDING_TYPE_HOUSE);
      this.build(this.BUILDING_TYPE_HUNTING_LODGE);
      this.build(this.BUILDING_TYPE_HUNTING_LODGE);
      this.build(this.BUILDING_TYPE_SAWMILL);
      this.priorities = [0, 0, 0, 0, 0, 0, 0];
      this.technologies = [false, false, false, false, false, false, false, false, false, false, false, false];
      return this.interval = setInterval(this.myLoop, 100);
    };

    Game.prototype.myLoop = function() {
      var boat, building, elem, i, j, mx, my, people, scoreTech, tech, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2, _ref3, _ref4;
      this.ctxFront.clearRect(0, 0, this.width, this.height);
      document.getElementById('pop_count').innerHTML = this.alivePeople;
      document.getElementById('mana_count').innerHTML = this.resources[0];
      document.getElementById('food_count').innerHTML = this.resources[1];
      document.getElementById('wood_count').innerHTML = this.resources[2];
      if (this.realInterval % 30 === 0) {
        this.nextTurn();
        this.addWeatherElements();
      }
      if (this.alivePeople < 1) {
        clearInterval(this.interval);
        scoreTech = 1;
        _ref = this.technologies;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tech = _ref[_i];
          if (tech) {
            scoreTech *= 5;
          }
        }
        this.score = scoreTech + this.maxPop * 4 + this.buildings.length * 10 + this.boats.length * 2;
        document.getElementById('count').innerHTML = this.score;
      }
      if (this.weatherDraw) {
        this.ctxWeather.clearRect(0, 0, this.width, this.height);
        if (this.weather === this.WEATHER_SNOW) {
          this.ctxWeather.globalAlpha = 0.2;
          this.ctxWeather.fillStyle = 'white';
          this.ctxWeather.fillRect(0, 0, this.width, this.height);
        } else if (this.weather === this.WEATHER_RAIN) {
          this.ctxWeather.globalAlpha = 0.3;
          this.ctxWeather.fillStyle = '#6088a4';
          this.ctxWeather.fillRect(0, 0, this.width, this.height);
        }
        _ref1 = this.weatherElements;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          elem = _ref1[_j];
          elem.posX += Math.round(Math.random() * 2);
          elem.posY += 1;
          elem.draw(this.ctxWeather);
        }
      }
      _ref2 = this.peoples;
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        people = _ref2[_k];
        if (!people.isDead && !people.walk()) {
          j = Math.round(Math.random() * this.map.heightMap);
          i = Math.round(Math.random() * this.map.widthMap);
          while (this.map.tiles[i][j].type === "water") {
            j = Math.round(Math.random() * this.map.heightMap);
            i = Math.round(Math.random() * this.map.widthMap);
          }
          people.findNewGoal(i * 50, j * 50);
        }
        people.draw(this.ctxFront);
      }
      _ref3 = this.boats;
      for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
        boat = _ref3[_l];
        mx = Math.floor(boat.posX / 50 + 0.5);
        my = Math.floor(boat.posY / 50 + 0.5);
        if (this.map.tiles[mx][my].type === "water" && !boat.navigate()) {
          if (this.technologies[this.TECH_MAP]) {
            j = boat.srcY + Math.round(Math.random() * 5 - 2);
            i = boat.srcX + Math.round(Math.random() * 5 - 2);
            while (i > 0 && j > 0 && i < this.map.widthMap && j < this.map.heightMap && this.map.tiles[i][j].type !== "water") {
              j = boat.srcY + Math.round(Math.random() * 5 - 2);
              i = boat.srcX + Math.round(Math.random() * 5 - 2);
            }
            boat.findNewGoal(i * 50 + 10, j * 50 + 10);
          } else {
            j = boat.srcY + Math.round(Math.random() * 3 - 1);
            i = boat.srcX + Math.round(Math.random() * 3 - 1);
            while (i > 0 && j > 0 && i < this.map.widthMap && j < this.map.heightMap && this.map.tiles[i][j].type !== "water") {
              j = boat.srcY + Math.round(Math.random() * 3 - 1);
              i = boat.srcX + Math.round(Math.random() * 3 - 1);
            }
            boat.findNewGoal(i * 50 + 10, j * 50 + 10);
          }
        }
        boat.draw(this.ctxFront);
      }
      _ref4 = this.buildings;
      for (_m = 0, _len4 = _ref4.length; _m < _len4; _m++) {
        building = _ref4[_m];
        building.draw(this.ctxBack);
      }
      return this.realInterval += 1;
    };

    Game.prototype.addPeople = function() {
      var building, houses, index, people, r, _i, _len, _ref;
      houses = [];
      _ref = this.buildings;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        building = _ref[_i];
        if (building.type === this.BUILDING_TYPE_HOUSE) {
          houses.push(building);
        }
      }
      if (!houses.length > 0) {
        r = Math.round(Math.random() * (this.spritePeopleElements.length - 1));
        people = new People(Math.round(this.map.widthMap / 2) * 50, Math.round(this.map.heightMap / 2) * 50, this.spritePeopleElements[r]);
      } else {
        index = Math.floor(Math.random() * houses.length);
        r = Math.round(Math.random() * (this.spritePeopleElements.length - 1));
        people = new People(houses[index].posX * 50 + 25, houses[index].posY * 50 + 25, this.spritePeopleElements[r]);
      }
      people.draw(this.ctxFront);
      this.peoples.push(people);
      return people;
    };

    Game.prototype.addWeatherElements = function() {
      var cloud, i, r, snow, _i;
      if (this.weather === this.WEATHER_SNOW) {
        r = Math.round(Math.random() * 5);
        for (i = _i = 0; 0 <= r ? _i <= r : _i >= r; i = 0 <= r ? ++_i : --_i) {
          snow = new Snow(Math.round(Math.random() * this.width / 10) - 100, Math.round(Math.random() * this.height));
          this.weatherElements.push(snow);
        }
        return this.weatherDraw = true;
      } else if (this.weather === this.WEATHER_WARM) {
        return console.log('warm');
      } else if (this.weather === this.WEATHER_RAIN) {
        this.ctxWeather.globalAlpha = 0.2;
        r = Math.random();
        if (r > 0.55) {
          cloud = new Cloud(Math.round(Math.random() * this.width / 15) - 100, Math.round(Math.random() * this.height));
          this.weatherElements.push(cloud);
        }
        return this.weatherDraw = true;
      }
    };

    Game.prototype.drawWeather = function() {
      var cloud, i, r, snow, _i, _j;
      if (this.weather === this.WEATHER_SNOW) {
        this.weatherElements = [];
        r = Math.round(Math.random() * 10) + 40;
        for (i = _i = 0; 0 <= r ? _i <= r : _i >= r; i = 0 <= r ? ++_i : --_i) {
          snow = new Snow(Math.round(Math.random() * this.width), Math.round(Math.random() * this.height));
          this.weatherElements.push(snow);
        }
        return this.weatherDraw = true;
      } else if (this.weather === this.WEATHER_WARM) {
        this.weatherElements = [];
        this.ctxWeather.clearRect(0, 0, this.width, this.height);
        this.ctxWeather.globalAlpha = 0.3;
        this.ctxWeather.fillStyle = '#f0df44';
        this.ctxWeather.fillRect(0, 0, this.width, this.height);
        return this.weatherDraw = false;
      } else if (this.weather === this.WEATHER_RAIN) {
        this.weatherElements = [];
        this.ctxWeather.globalAlpha = 0.2;
        r = Math.round(Math.random() * 10) + 5;
        for (i = _j = 0; 0 <= r ? _j <= r : _j >= r; i = 0 <= r ? ++_j : --_j) {
          cloud = new Cloud(Math.round(Math.random() * this.width), Math.round(Math.random() * this.height));
          this.weatherElements.push(cloud);
        }
        return this.weatherDraw = true;
      } else {
        this.ctxWeather.globalAlpha = 0;
        return this.ctxWeather.clearRect(0, 0, this.width, this.height);
      }
    };

    Game.prototype.nextTurn = function() {
      var boat, bornCounter, building, coldDie, deadIndex, foodCapacity, foodToAdd, hunterCount, i, iPeople, j, k, killCounter, manaToAdd, maxIndex, maxMana, maxPeople, mountainCount, numberOfBorn, numberOfDeath, oldWeather, people, peoplesToDel, priority, speople, sum, templeCount, woodCapacity, woodToAdd, x, y, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _len6, _len7, _len8, _len9, _m, _n, _o, _p, _q, _r, _ref, _ref1, _ref10, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9, _s, _t;
      oldWeather = this.weather;
      foodCapacity = 20;
      woodCapacity = 5;
      numberOfDeath = 0;
      _ref = this.buildings;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        building = _ref[_i];
        if (building.type === this.BUILDING_TYPE_GRANARY) {
          foodCapacity += 30;
        }
        if (building.type === this.BUILDING_TYPE_SAWMILL) {
          woodCapacity += 20;
        }
      }
      this.alivePeople = this.peoples.length;
      _ref1 = this.peoples;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        people = _ref1[_j];
        if (people.isDead) {
          this.alivePeople--;
        }
      }
      sum = this.alivePeople * this.FOOD_COMSUPTION;
      if (sum > this.resources[this.FOOD]) {
        numberOfDeath = sum - this.resources[this.FOOD];
        this.resources[this.FOOD] = 0;
        this.priorities[this.PRIORITY_FOOD] = numberOfDeath * 4;
      } else {
        this.priorities[this.PRIORITY_FOOD] = (foodCapacity - this.resources[this.FOOD]) / 3;
        this.resources[this.FOOD] -= sum;
      }
      foodToAdd = 0;
      woodToAdd = 0;
      manaToAdd = 1;
      maxPeople = 5;
      maxMana = 15;
      _ref2 = this.boats;
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        boat = _ref2[_k];
        x = Math.round(boat.posX / 50);
        y = Math.round(boat.posY / 50);
        if ((this.map.tiles[x][y] != null) && this.map.tiles[x][y].res > 0 && this.map.tiles[x][y] === "water") {
          this.map.tiles[x][y].res--;
          foodToAdd += this.FOOD_BOAT;
        }
      }
      _ref3 = this.buildings;
      for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
        building = _ref3[_l];
        if (this.map.tiles[building.posX][building.posY].res <= 0) {
          continue;
        }
        this.map.tiles[building.posX][building.posY].res--;
        switch (building.type) {
          case this.BUILDING_TYPE_TEMPLE:
            manaToAdd++;
            maxMana += 15;
            break;
          case this.BUILDING_TYPE_FARM:
            foodToAdd += this.FOOD_FARM;
            break;
          case this.BUILDING_TYPE_PASTURE:
            foodToAdd += this.FOOD_PASTURE;
            break;
          case this.BUILDING_TYPE_HUNTING_LODGE:
            if (this.technologies[this.TECH_FIRE]) {
              foodToAdd += this.FOOD_HUNTING_FIRE;
            } else {
              foodToAdd += this.FOOD_HUNTING;
            }
            break;
          case this.BUILDING_TYPE_SAWMILL:
            woodToAdd += 4;
            break;
          case this.BUILDING_TYPE_HOUSE:
            if (this.technologies[this.TECH_ARCHITECTURE]) {
              maxPeople += 12;
            } else {
              maxPeople += 9;
            }
        }
      }
      if (this.resources[this.MANA] + manaToAdd > maxMana) {
        manaToAdd = maxMana - this.resources[this.MANA];
      }
      if (this.resources[this.FOOD] + foodToAdd > foodCapacity) {
        this.priorities[this.PRIORITY_GRANARY] = foodToAdd;
        foodToAdd = foodCapacity - this.resources[this.FOOD];
      }
      if (this.resources[this.WOOD] + woodToAdd > woodCapacity) {
        woodToAdd = woodCapacity - this.resources[this.WOOD];
      }
      this.resources[this.FOOD] += foodToAdd;
      this.resources[this.WOOD] += woodToAdd;
      this.resources[this.MANA] += manaToAdd;
      killCounter = numberOfDeath;
      while (killCounter > 0) {
        deadIndex = Math.floor(Math.random() * this.peoples.length);
        if (!this.peoples[deadIndex].isDead) {
          killCounter--;
          this.peoples[deadIndex].isDead = true;
        }
      }
      peoplesToDel = [];
      _ref4 = this.peoples;
      for (_m = 0, _len4 = _ref4.length; _m < _len4; _m++) {
        people = _ref4[_m];
        if (people.isDead) {
          people.timeDead++;
          if (people.timeDead > 5) {
            peoplesToDel.push(people);
          }
        }
      }
      for (_n = 0, _len5 = peoplesToDel.length; _n < _len5; _n++) {
        iPeople = peoplesToDel[_n];
        this.peoples.splice(this.peoples.indexOf(iPeople), 1);
      }
      this.priorities[this.PRIORITY_FAITH]++;
      if (numberOfDeath > 0) {
        numberOfBorn = 0.125 * Math.random() * this.alivePeople;
      } else {
        numberOfBorn = Math.random() * this.alivePeople;
      }
      _ref5 = this.peoples;
      for (k = _o = 0, _len6 = _ref5.length; _o < _len6; k = ++_o) {
        speople = _ref5[k];
        speople.age++;
        if (Math.random() * this.MAX_AGE < speople.age) {
          if (!speople.isDead) {
            speople.isDead = true;
          }
        }
      }
      bornCounter = Math.floor(numberOfBorn);
      while (bornCounter > 0) {
        bornCounter--;
        if (maxPeople === this.alivePeople) {
          this.priorities[this.PRIORITY_HOUSE] += 3;
        } else {
          this.addPeople();
        }
      }
      maxIndex = 0;
      _ref6 = this.priorities;
      for (k = _p = 0, _len7 = _ref6.length; _p < _len7; k = ++_p) {
        priority = _ref6[k];
        if (priority > this.priorities[maxIndex]) {
          maxIndex = k;
        }
      }
      this.commonSenseBuild(maxIndex);
      if (this.weather === this.WEATHER_SNOW) {
        coldDie = Math.random() * 10 < 2;
        if (coldDie) {
          if (this.technologies[this.TECH_FIRE]) {
            killCounter = 1 / 10 * this.alivePeople;
          } else {
            killCounter = 1 / 3 * this.alivePeople;
          }
          while (killCounter > 0) {
            deadIndex = Math.floor(Math.random() * this.peoples.length);
            if (!this.peoples[deadIndex].isDead) {
              killCounter--;
              this.peoples[deadIndex].isDead = true;
              this.DEATH_FROM_ICE++;
            }
          }
        }
      }
      if (!this.technologies[this.TECH_FIRE] && this.weather === this.WEATHER_RAIN && this.DEATH_FROM_ICE >= 5) {
        this.discover(this.TECH_FIRE);
      }
      if (!this.technologies[this.TECH_WHEEL]) {
        mountainCount = 0;
        for (i = _q = 0, _ref7 = this.map.widthMap; 0 <= _ref7 ? _q <= _ref7 : _q >= _ref7; i = 0 <= _ref7 ? ++_q : --_q) {
          for (j = _r = 0, _ref8 = this.map.heightMap; 0 <= _ref8 ? _r <= _ref8 : _r >= _ref8; j = 0 <= _ref8 ? ++_r : --_r) {
            if (this.map.tiles[i][j].type === "mountain") {
              mountainCount++;
            }
          }
        }
        if (mountainCount > 2) {
          this.discover(this.TECH_WHEEL);
        }
      }
      if (!this.technologies[this.TECH_AGRICULTURE] && this.technologies[this.TECH_WHEEL] && this.alivePeople > 50 && this.weather === this.WEATHER_WARM) {
        this.discover(this.TECH_AGRICULTURE);
      }
      if (!this.technologies[this.TECH_BREEDING] && this.technologies[this.TECH_FIRE]) {
        hunterCount = 0;
        _ref9 = this.buildings;
        for (_s = 0, _len8 = _ref9.length; _s < _len8; _s++) {
          building = _ref9[_s];
          if (building.type === this.BUILDING_TYPE_HUNTING_LODGE) {
            hunterCount++;
          }
        }
        if (hunterCount > 5) {
          this.discover(this.TECH_BREEDING);
        }
      }
      if (!this.technologies[this.TECH_PAPER] && this.technologies[this.TECH_FIRE] && this.peoples.length > 100) {
        this.discover(this.TECH_PAPER);
      }
      if (!this.technologies[this.TECH_ARCHITECTURE] && this.technologies[this.TECH_PAPER] && this.peoples.length > 200) {
        templeCount = 0;
        _ref10 = this.buildings;
        for (_t = 0, _len9 = _ref10.length; _t < _len9; _t++) {
          building = _ref10[_t];
          if (building.type === this.BUILDING_TYPE_TEMPLE) {
            templeCount++;
          }
        }
        this.discover(this.TECH_ARCHITECTURE);
      }
      if (!this.technologies[this.TECH_FISH] && this.resources[this.WOOD] >= 80) {
        this.discover(this.TECH_FISH);
      }
      if (!this.technologies[this.TECH_FISH] && this.resources[this.WOOD] >= 80) {
        this.discover(this.TECH_FISH);
      }
      if (!this.technologies[this.TECH_MAP] && this.technologies[this.TECH_PAPER] && this.technologies[this.TECH_FISH] && boats.length > 5) {
        this.discover(this.TECH_MAP);
      }
      if (oldWeather !== this.weather) {
        this.timeSameWeather = 0;
      } else {
        this.timeSameWeather++;
      }
      if (this.technologies[this.TECH_FISH] && this.BUILDING_NUMBER_HARBOR === 0) {
        return this.priorities[this.PRIORITY_HARBOR] += 3;
      }
    };

    Game.prototype.discover = function(indexTechno) {
      var name;
      this.technologies[indexTechno] = true;
      name = '';
      if (indexTechno === this.TECH_ARCHITECTURE) {
        name = 'architecture';
      } else if (indexTechno === this.TECH_PAPER) {
        name = 'paper';
      } else if (indexTechno === this.TECH_FIRE) {
        name = 'fire';
      } else if (indexTechno === this.TECH_BREEDING) {
        name = 'breeding';
      } else if (indexTechno === this.TECH_WHEEL) {
        name = 'wheel';
      } else if (indexTechno === this.TECH_AGRICULTURE) {
        name = 'agriculture';
      } else if (indexTechno === this.TECH_FISH) {
        name = 'fish';
      } else if (indexTechno === this.TECH_MAP) {
        name === 'map';
      }
      document.getElementById('technos').innerHTML = 'You just discovered ' + name + '!';
      return console.log('DISCOVERED ' + name);
    };

    Game.prototype.commonSenseBuild = function(maxIndex) {
      switch (maxIndex) {
        case this.PRIORITY_GRANARY:
          if (this.build(this.BUILDING_TYPE_GRANARY)) {
            return this.priorities[this.PRIORITY_GRANARY] = 0;
          } else {
            return this.priorities[this.PRIORITY_WOOD] += this.GRANARY_COST;
          }
          break;
        case this.PRIORITY_WOOD:
          if (this.build(this.BUILDING_TYPE_SAWMILL)) {
            return this.priorities[this.PRIORITY_WOOD] = 0;
          } else {
            return this.priorities[this.PRIORITY_WOOD] += this.SAWMILL_COST;
          }
          break;
        case this.PRIORITY_FAITH:
          if (this.build(this.BUILDING_TYPE_TEMPLE)) {
            return this.priorities[this.PRIORITY_FAITH] = 0;
          } else {
            return this.priorities[this.PRIORITY_WOOD] += this.TEMPLE_COST;
          }
          break;
        case this.PRIORITY_FOOD:
          if (this.technologies[this.TECH_FISH] && this.BUILDING_NUMBER_HARBOR > 0 && this.resources[this.WOOD] > this.BOAT_COST && this.boats.length < 5) {
            this.buildABoat();
            return this.priorities[this.PRIORITY_FOOD] = 0;
          } else if (this.build(this.BUILDING_TYPE_PASTURE) || this.build(this.BUILDING_TYPE_FARM) || this.build(this.BUILDING_TYPE_HUNTING_LODGE)) {
            return this.priorities[this.PRIORITY_FOOD] = 0;
          } else {
            return this.priorities[this.PRIORITY_WOOD] += this.PASTURE_COST;
          }
          break;
        case this.PRIORITY_HOUSE:
          if (this.build(this.BUILDING_TYPE_HOUSE)) {
            return this.priorities[this.PRIORITY_HOUSE] = 0;
          } else {
            return this.priorities[this.PRIORITY_WOOD] += this.HOUSE_COST;
          }
          break;
        case this.PRIORITY_HARBOR:
          if (this.build(this.BUILDING_TYPE_HARBOR)) {
            return this.priorities[this.PRIORITY_HARBOR] = 0;
          } else {
            return this.priorities[this.PRIORITY_WOOD] += this.HARBOR_COST;
          }
      }
    };

    Game.prototype.buildABoat = function() {
      var building, harborList, indn, _i, _len, _ref;
      harborList = [];
      _ref = this.buildings;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        building = _ref[_i];
        if (building.type === this.BUILDING_TYPE_HARBOR) {
          harborList.push(building);
        }
      }
      if (harborList.length > 0) {
        indn = Math.floor(Math.random() * harborList.length);
        building = harborList[indn];
        return this.boats.push(new Boat(building.posX * 50, building.posY * 50));
      }
    };

    Game.prototype.build = function(type) {
      var building, pos;
      switch (type) {
        case this.BUILDING_TYPE_TEMPLE:
          if (this.TEMPLE_COST > this.resources[this.WOOD]) {
            return false;
          }
          pos = this.findSlot("sand");
          if (pos[0] === -1) {
            pos = this.findSlot("grass");
            if (pos[0] === -1) {
              return true;
            }
          }
          building = new Building(this.BUILDING_TYPE_TEMPLE, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.TEMPLE_COST;
          return true;
        case this.BUILDING_TYPE_HUNTING_LODGE:
          console.log("I WANT TO BUILD HUNTING LODGE :" + this.HUNTING_LODGE_COST + " > " + this.resources[this.WOOD]);
          if (this.HUNTING_LODGE_COST > this.resources[this.WOOD]) {
            return false;
          }
          pos = this.findSlot("grass");
          if (pos[0] === -1) {
            return true;
          }
          building = new Building(this.BUILDING_TYPE_HUNTING_LODGE, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.HUNTING_LODGE_COST;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
        case this.BUILDING_TYPE_PASTURE:
          console.log("I WANT TO BUILD PASTURE :" + this.PASTURE_COST + " > " + this.resources[this.WOOD]);
          if (!this.technologies[this.TECH_BREEDING] || this.PASTURE_COST > this.resources[this.WOOD]) {
            return false;
          }
          pos = this.findSlot("mountain");
          if (pos[0] === -1) {
            return true;
          }
          building = new Building(this.BUILDING_TYPE_PASTURE, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.PASTURE_COST;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
        case this.BUILDING_TYPE_HOUSE:
          console.log("I WANT TO BUILD HOUSE :" + this.HOUSE_COST + " > " + this.resources[this.WOOD]);
          if (this.HOUSE_COST > this.resources[this.WOOD]) {
            return false;
          }
          pos = this.findSlot("grass");
          if (pos[0] === -1) {
            return true;
          }
          building = new Building(this.BUILDING_TYPE_HOUSE, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.HOUSE_COST;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
        case this.BUILDING_TYPE_FARM:
          console.log("I WANT TO BUILD FARM :" + this.FARM_COST + " > " + this.resources[this.WOOD]);
          if (this.FARM_COST > this.resources[this.WOOD] || !this.technologies[this.TECH_AGRICULTURE]) {
            return false;
          }
          pos = this.findSlot("grass");
          if (pos[0] === -1) {
            return true;
          }
          building = new Building(this.BUILDING_TYPE_FARM, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.FARM_COST;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
        case this.BUILDING_TYPE_GRANARY:
          console.log("I WANT TO BUILD GRANARY :" + this.GRANARY_COST + " > " + this.resources[this.WOOD]);
          if (this.GRANARY_COST > this.resources[this.WOOD]) {
            return false;
          }
          pos = this.findSlot("grass");
          if (pos[0] === -1) {
            return true;
          }
          building = new Building(this.BUILDING_TYPE_GRANARY, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.GRANARY_COST;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
        case this.BUILDING_TYPE_SAWMILL:
          console.log("I WANT TO BUILD SAWMILL :" + this.SAWMILL_COST + " > " + this.resources[this.WOOD]);
          if (this.SAWMILL_COST > this.resources[this.WOOD]) {
            return false;
          }
          pos = this.findSlot("mountain");
          if (pos[0] === -1) {
            pos = this.findSlot("grass");
            if (pos[0] === -1) {
              return true;
            }
          }
          building = new Building(this.BUILDING_TYPE_SAWMILL, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.SAWMILL_COST;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
        case this.BUILDING_TYPE_HARBOR:
          console.log("I WANT TO BUILD HARBOR :" + this.HARBOR_COST + " > " + this.resources[this.WOOD]);
          if (this.HARBOR_COST > this.resources[this.WOOD] || !this.technologies[this.TECH_FISH]) {
            return false;
          }
          pos = this.findSlot("harbor");
          if (pos[0] === -1) {
            return true;
          }
          building = new Building(this.BUILDING_TYPE_HARBOR, this.spriteBuildings);
          building.posX = pos[0];
          building.posY = pos[1];
          this.map.tiles[pos[0]][pos[1]].building = building;
          this.buildings.push(building);
          this.resources[this.WOOD] -= this.HARBOR_COST;
          this.BUILDING_NUMBER_HARBOR++;
          console.log("SUCCESS : final wood " + this.resources[this.WOOD]);
          return true;
      }
    };

    Game.prototype.findSlot = function(searchType) {
      var ce, co, i, index, j, notWaterCounter, results, _i, _j, _k, _l, _m, _n, _ref, _ref1, _ref2, _ref3;
      results = [];
      if (searchType === "harbor") {
        console.log("I GONNA BUILD A HARBOR :) ");
        for (i = _i = 0, _ref = this.map.widthMap; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          for (j = _j = 0, _ref1 = this.map.heightMap; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
            if (this.map.tiles[i][j].type === "water" && this.map.tiles[i][j].building === null) {
              notWaterCounter = 0;
              for (co = _k = -1; _k <= 2; co = ++_k) {
                for (ce = _l = -1; _l <= 2; ce = ++_l) {
                  if (i + co > 0 && j + ce > 0 && i + co < this.map.widthMap && j + ce < this.map.heightMap && this.map.tiles[i + co][j + ce].type !== "water") {
                    notWaterCounter++;
                  }
                }
              }
              if (notWaterCounter > 1) {
                results.push([i, j]);
              }
            }
          }
        }
        if (results.length > 0) {
          i = Math.floor(Math.random() * results.length);
          return results[i];
        }
        return [-1, -1];
      }
      for (i = _m = 0, _ref2 = this.map.widthMap; 0 <= _ref2 ? _m <= _ref2 : _m >= _ref2; i = 0 <= _ref2 ? ++_m : --_m) {
        for (j = _n = 0, _ref3 = this.map.heightMap; 0 <= _ref3 ? _n <= _ref3 : _n >= _ref3; j = 0 <= _ref3 ? ++_n : --_n) {
          if (this.map.tiles[i][j].type === searchType && this.map.tiles[i][j].building === null) {
            results.push([i, j]);
          }
        }
      }
      if (results.length > 0) {
        index = Math.floor(Math.random() * results.length);
        return results[index];
      }
      return [-1, -1];
    };

    return Game;

  })();

  if (typeof module !== 'undefined' && module.exports) {
    exports.Game = Game;
  } else {
    window.Game = Game;
  }

}).call(this);
