// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    return window.onload = function() {
      var canvas, ctx, i, img, j, nbX, nbY, r, _i, _results;
      canvas = document.getElementById('c');
      ctx = canvas.getContext('2d');
      canvas.width = document.body.clientWidth;
      canvas.height = document.body.clientHeight;
      img = new Image();
      img.src = 'img/spriteGlobal.png';
      nbX = canvas.width / 10;
      nbY = canvas.height / 10;
      _results = [];
      for (i = _i = 0; 0 <= nbX ? _i <= nbX : _i >= nbX; i = 0 <= nbX ? ++_i : --_i) {
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (j = _j = 0; 0 <= nbY ? _j <= nbY : _j >= nbY; j = 0 <= nbY ? ++_j : --_j) {
            r = Math.random() >= 0.5 ? 0 : 10;
            _results1.push(ctx.drawImage(img, r, 10, 10, 10, i * 10, j * 10, 10, 10));
          }
          return _results1;
        })());
      }
      return _results;
    };
  });

}).call(this);
