// Generated by CoffeeScript 1.9.0
(function() {
  window.onload = function() {
    var backVideoCanvas, backVideoCtx, blobDetector, canvasBack, canvasDebug, canvasFront, canvasWeather, ctxBack, ctxDebug, ctxFront, ctxWeather, cv, debugCanvas, debugCtx, debugVideoCanvas, debugVideoCtx, frontVideoCanvas, frontVideoCtx, game, video, webcam;
    $('#loading').hide();
    canvasFront = document.getElementById('front');
    ctxFront = canvasFront.getContext('2d');
    canvasBack = document.getElementById('back');
    ctxBack = canvasBack.getContext('2d');
    window.ctxBack = ctxBack;
    canvasDebug = document.getElementById('frontDebug');
    ctxDebug = canvasBack.getContext('2d');
    canvasWeather = document.getElementById('weather');
    ctxWeather = canvasWeather.getContext('2d');
    canvasBack.width = document.body.clientWidth;
    canvasBack.height = document.body.clientHeight;
    canvasFront.width = document.body.clientWidth;
    canvasFront.height = document.body.clientHeight;
    canvasDebug.width = document.body.clientWidth;
    canvasDebug.height = document.body.clientHeight;
    canvasWeather.width = document.body.clientWidth;
    canvasWeather.height = document.body.clientHeight;
    game = new Game(ctxFront, ctxBack, ctxWeather, document.body.clientWidth, document.body.clientHeight);
    game.init();
    window.game = game;
    webcam = document.getElementById('webcam');
    window.webcam = webcam;
    frontVideoCanvas = document.getElementById('frontVideo');
    frontVideoCtx = frontVideoCanvas.getContext('2d');
    window.frontVideoCanvas = frontVideoCanvas;
    backVideoCanvas = document.getElementById('backVideo');
    backVideoCtx = backVideoCanvas.getContext('2d');
    window.backVideoCtx = backVideoCtx;
    debugVideoCanvas = document.getElementById('frontVideoDebug');
    debugVideoCtx = debugVideoCanvas.getContext('2d');
    debugCanvas = document.getElementById('frontDebug');
    debugCtx = debugCanvas.getContext('2d');
    cv = new Cv(backVideoCanvas);
    window.cv = cv;
    blobDetector = new BlobDetector(Cv, backVideoCanvas);
    window.blobDetector = blobDetector;
    video = new Video(webcam, frontVideoCanvas, frontVideoCtx, backVideoCanvas, backVideoCtx, debugCanvas, debugCtx, game);
    window.video = video;
    document.getElementById('speech_result').onwebkitspeechchange = function(val) {
      if (game.resources[game.MANA] >= 10) {
        game.resources[game.MANA] -= 10;
        switch (val.target.value) {
          case 'rain':
          case 'brain':
          case 'wayne':
            game.weather = game.WEATHER_RAIN;
            break;
          case 'warm':
          case 'worm':
            game.weather = game.WEATHER_WARM;
            break;
          case 'snow':
          case 'no':
          case 'note':
          case 'stove':
            game.weather = game.WEATHER_SNOW;
            break;
          case 'sun':
            game.weather = game.WEATHER_SUN;
            break;
          default:
            game.resources[game.MANA] += 10;
        }
        return game.drawWeather(ctxWeather);
      }
    };
    document.getElementById('technos').addEventListener('DOMSubtreeModified', function() {
      return $('#technos').show().fadeOut(3000);
    }, false);
    return document.getElementById('count').addEventListener('DOMSubtreeModified', function() {
      return $('#score').show().fadeIn(400);
    }, false);
  };

}).call(this);
