// Generated by CoffeeScript 1.9.0
(function() {
  var MapElement;

  MapElement = (function() {
    function MapElement(_at_type, spritesheetGlobal, size) {
      var i, _i;
      this.type = _at_type;
      this.sprites = null;
      this.spritesC = [];
      this.tiles = [];
      switch (this.type) {
        case "water":
          this.sprites = [new SpriteElement(spritesheetGlobal, 0, 1), new SpriteElement(spritesheetGlobal, 1, 1)];
          break;
        case "grass":
          this.sprites = [new SpriteElement(spritesheetGlobal, 0, 0), new SpriteElement(spritesheetGlobal, 1, 0)];
          for (i = _i = 2; _i <= 10; i = ++_i) {
            this.spritesC.push(new SpriteElement(spritesheetGlobal, i, 0));
          }
          break;
        case "sand":
          this.sprites = [new SpriteElement(spritesheetGlobal, 0, 2), new SpriteElement(spritesheetGlobal, 1, 2)];
          break;
        case "mountain":
          this.sprites = [new SpriteElement(spritesheetGlobal, 0, 3)];
      }
      this.size = size / spritesheetGlobal.offset;
      this.building = null;
      if (this.type === "water") {
        this.res = 200;
      } else {
        this.res = 50;
      }
      this.init();
    }

    MapElement.prototype.init = function() {
      var i, j, numTem, temp, _i, _j, _ref, _ref1, _results;
      _results = [];
      for (i = _i = 0, _ref = this.size; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        temp = [];
        for (j = _j = 0, _ref1 = this.size; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
          numTem = Math.round(Math.random() * (this.sprites.length - 1));
          temp.push(this.sprites[numTem]);
        }
        _results.push(this.tiles.push(temp));
      }
      return _results;
    };

    MapElement.prototype.draw = function(ctx, x, y) {
      var i, j, spriteElem, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = this.size; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (j = _j = 0, _ref1 = this.size; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
            spriteElem = this.tiles[i][j];
            _results1.push(ctx.drawImage(spriteElem.spritesheet.image, spriteElem.i * 10, spriteElem.j * 10, 10, 10, x * 50 + i * 10, y * 50 + j * 10, 10, 10));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    MapElement.prototype.changePixel = function(i, j, sprites) {
      var numTem;
      numTem = Math.round(Math.random() * (sprites.length - 1));
      return this.tiles[i][j] = sprites[numTem];
    };

    return MapElement;

  })();

  window.MapElement = MapElement;

}).call(this);
