// Generated by CoffeeScript 1.10.0
(function() {
  var People;

  People = (function() {
    function People(posX, posY, spriteElement) {
      this.posX = posX;
      this.posY = posY;
      this.spriteElement = spriteElement != null ? spriteElement : null;
      this.path = [];
      this.state = 'IDLE';
      this.goal = [-1, -1];
      this.age = 0;
      this.timeDead = 0;
      this.isDead = false;
    }

    People.prototype.walk = function() {
      var dirX, dirY;
      if (this.goal[0] < 0) {
        return false;
      }
      if (Math.abs(this.goal[0] - this.posX) < 3 && Math.abs(this.goal[1] - this.posY) < 3) {
        return false;
      }
      dirX = 0;
      dirY = 0;
      if (this.posX > this.goal[0]) {
        dirX = -1;
      }
      if (this.posX < this.goal[0]) {
        dirX = 1;
      }
      if (this.posY > this.goal[1]) {
        dirY = -1;
      }
      if (this.posY < this.goal[1]) {
        dirY = 1;
      }
      this.posX += Math.floor(Math.random() * 5) - 2 + dirX;
      this.posY += Math.floor(Math.random() * 5) - 2 + dirY;
      return true;
    };

    People.prototype.findNewGoal = function(x, y) {
      return this.goal = [x, y];
    };

    People.prototype.draw = function(ctx) {
      if (!this.isDead) {
        return ctx.drawImage(this.spriteElement.spritesheet.image, this.spriteElement.i * 8, this.spriteElement.j * 8, 8, 8, this.posX, this.posY, 8, 8);
      } else {
        return ctx.drawImage(this.spriteElement.spritesheet.image, 0, 8, 8, 8, this.posX, this.posY, 8, 8);
      }
    };

    People.prototype.setDead = function() {
      this.spriteElement.i = 1;
      return this.spriteElement.j = 0;
    };

    return People;

  })();

  window.People = People;

}).call(this);
