// Generated by CoffeeScript 1.10.0
(function() {
  var SpriteElement;

  SpriteElement = (function() {
    function SpriteElement(spritesheet, i, j) {
      this.spritesheet = spritesheet;
      this.i = i;
      this.j = j;
    }

    return SpriteElement;

  })();

  window.SpriteElement = SpriteElement;

}).call(this);
