// Generated by CoffeeScript 1.9.0
(function() {
  var Spritesheet;

  Spritesheet = (function() {
    function Spritesheet(_at_path, _at_offset) {
      this.path = _at_path;
      this.offset = _at_offset;
      this.image = new Image();
      this.image.src = this.path;
    }

    return Spritesheet;

  })();

  if (typeof module !== 'undefined' && module.exports) {
    exports.Spritesheet = Spritesheet;
  } else {
    window.Spritesheet = Spritesheet;
  }

}).call(this);
