// Generated by CoffeeScript 1.10.0
(function() {
  var Spritesheet;

  Spritesheet = (function() {
    function Spritesheet(path, offset) {
      this.path = path;
      this.offset = offset;
      this.image = new Image();
      this.image.src = this.path;
    }

    return Spritesheet;

  })();

  if (typeof module !== 'undefined' && module.exports) {
    exports.Spritesheet = Spritesheet;
  } else {
    window.Spritesheet = Spritesheet;
  }

}).call(this);
