// Generated by CoffeeScript 1.9.0
(function() {
  var SpriteElement;

  SpriteElement = (function() {
    function SpriteElement(_at_spritesheet, _at_i, _at_j) {
      this.spritesheet = _at_spritesheet;
      this.i = _at_i;
      this.j = _at_j;
    }

    return SpriteElement;

  })();

  window.SpriteElement = SpriteElement;

}).call(this);
