// Generated by CoffeeScript 1.9.0
(function() {
  var Cloud, Snow, WeatherElement,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  WeatherElement = (function() {
    function WeatherElement(_at_posX, _at_posY) {
      this.posX = _at_posX != null ? _at_posX : 0;
      this.posY = _at_posY != null ? _at_posY : 0;
    }

    return WeatherElement;

  })();

  Cloud = (function(_super) {
    __extends(Cloud, _super);

    function Cloud(_at_posX, _at_posY) {
      var r;
      this.posX = _at_posX != null ? _at_posX : 0;
      this.posY = _at_posY != null ? _at_posY : 0;
      this.image = new Image();
      this.image.src = 'img/cloud.png';
      r = Math.random();
      this.width = Math.round(r * 251);
      this.height = Math.round(r * 188);
    }

    Cloud.prototype.draw = function(ctx) {
      ctx.globalAlpha = 0.2;
      return ctx.drawImage(this.image, this.posX, this.posY, this.width, this.height);
    };

    return Cloud;

  })(WeatherElement);

  if (typeof module !== 'undefined' && module.exports) {
    exports.Cloud = Cloud;
  } else {
    window.Cloud = Cloud;
  }

  Snow = (function(_super) {
    __extends(Snow, _super);

    function Snow(_at_posX, _at_posY) {
      this.posX = _at_posX != null ? _at_posX : 0;
      this.posY = _at_posY != null ? _at_posY : 0;
      this.image = new Image();
      this.image.src = 'img/snow.png';
      this.width = 251;
      this.height = 188;
    }

    Snow.prototype.draw = function(ctx) {
      return ctx.drawImage(this.image, this.posX, this.posY, this.width, this.height);
    };

    return Snow;

  })(WeatherElement);

  window.Snow = Snow;

}).call(this);
