// Generated by CoffeeScript 1.10.0
(function() {
  var Cloud, Snow, WeatherElement,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  WeatherElement = (function() {
    function WeatherElement(posX, posY) {
      this.posX = posX != null ? posX : 0;
      this.posY = posY != null ? posY : 0;
    }

    return WeatherElement;

  })();

  Cloud = (function(superClass) {
    extend(Cloud, superClass);

    function Cloud(posX, posY) {
      var r;
      this.posX = posX != null ? posX : 0;
      this.posY = posY != null ? posY : 0;
      this.image = new Image();
      this.image.src = 'img/cloud.png';
      r = Math.random();
      this.width = Math.round(r * 251);
      this.height = Math.round(r * 188);
    }

    Cloud.prototype.draw = function(ctx) {
      ctx.globalAlpha = 0.2;
      return ctx.drawImage(this.image, this.posX, this.posY, this.width, this.height);
    };

    return Cloud;

  })(WeatherElement);

  if (typeof module !== 'undefined' && module.exports) {
    exports.Cloud = Cloud;
  } else {
    window.Cloud = Cloud;
  }

  Snow = (function(superClass) {
    extend(Snow, superClass);

    function Snow(posX, posY) {
      this.posX = posX != null ? posX : 0;
      this.posY = posY != null ? posY : 0;
      this.image = new Image();
      this.image.src = 'img/snow.png';
      this.width = 251;
      this.height = 188;
    }

    Snow.prototype.draw = function(ctx) {
      return ctx.drawImage(this.image, this.posX, this.posY, this.width, this.height);
    };

    return Snow;

  })(WeatherElement);

  window.Snow = Snow;

}).call(this);
